---
title: "Research"
---

### Publications

Iasmin Goes and [Terrence L. Chapman](https://terrencechapman.weebly.com/). 2024. "Can 'Soft' Advice From International Organizations Catalyze Natural Resource Sector Reform?" Forthcoming, *International Studies Quarterly*. [PDF (Pre-Print)](papers/Goes-Chapman.pdf)

Iasmin Goes (2023). "New Data, New Results? How Data Sources and Vintages Affect the Replicability of Research." *Research & Politics* 10(2):1--13. [PDF (Open Access)](https://doi.org/10.1177/20531680231170502) \| [Replication Materials](https://doi.org/10.7910/DVN/G9QZOU)

Iasmin Goes (2023). "Examining the Effect of IMF Conditionality on Natural Resource Policy." *Economics & Politics* 35(1):227--285. [PDF (Open Access)](https://doi.org/10.1111/ecpo.12214) \| [Replication Materials](https://doi.org/10.7910/DVN/9RURWP)

Iasmin Goes (2022). "Electoral Politics, Fiscal Policy, and the Resource Curse." *Studies in Comparative International Development* 57:525--576. [PDF (Gated)](https://doi.org/10.1007/s12116-022-09367-8) \| [PDF (Ungated, View Only)](https://rdcu.be/cU1nr) \| [Replication Materials](https://doi.org/10.7910/DVN/8HUQIF)

Iasmin Goes (2013). "Between Truth and Amnesia: State Terrorism, Human Rights Violations and Transitional Justice in Brazil." *European Review of Latin America and the Caribbean* 94:83--96. [PDF (Open Access)](http://doi.org/10.18352/erlacs.8395)

### Working Papers

Iasmin Goes and [Stephen B. Kaplan](http://stephenbkaplan.com/). "Crude Credit: The Political Economy of Global Finance and Natural Resource Wealth." Revised & Resubmitted. [PDF](papers/Goes-Kaplan.pdf)

Iasmin Goes. "Mismeasuring the World: Predicting Uncertainty in International Statistics." Under Review. [PDF](papers/Goes-WDI.pdf)

[Ariana Ribeiro Costa](https://ri.fgv.br/en/pessoas/ariana-ribeiro-costa), Iasmin Goes, and [Carolina Moehlecke](https://www.carolinamoehlecke.com/). "The Determinants of FDI Inflows: Evidence from Firm and Municipality-Level Data in Brazil."

Iasmin Goes and [Daniel Weitzel](https://www.danweitzel.net/). "You Should (Probably) Not Split Your Sample.
